INSERT INTO users ( user_name,
                    password,
                    nickname,
                    email,
                    roles,
                    pictureURL,
                    is_non_banned,
                    ban_expiration)
 VALUES(    'Admin',
            '$2a$10$toADtYnTZksrJrdj41sIoeW2ZjdXnBvjYg4AxfMId17Q7GEEm1i0O',
            'Admin',
            'admin@admin-help.cz',
            'ADMIN',
            'profilePic/defaultPic.jpg',
            TRUE,
            NULL);
